top = "置顶歌曲"
join = "加入频道"
play = "播放歌曲"
pause = "暂停歌曲"
resume = "继续播放"
skip = "跳过歌曲"
queue = "显示列表"
delete = "删除歌曲"
skipto = "跳至歌曲"
current = "正在播放"
leave = "离开频道"
search = "搜索歌曲"
skipall = "清空列表"
random = "乱序列表"

load = "加载个人列表或频道历史记录"
save = "保存个人列表链接"

clear = "清空本频道聊天记录"
tts = "嘴替文字转语音"
maze = "This command sends a maze to the channel"
report = "This command reports a bug to the developer"
help = "This command will show all commands and their description"

minecraft = "This command will show the minecraft server status"
chatgpton = "This command will turn on the chatbot"
chatgptoff = "This command will turn off the chatbot"
chatgptChatChannel = "This command will set the chatbot chat channel"
chatgptMusicChannel = "This command will set the chatbot music channel"
chatgptChatChannelDelete = "This command will turn off chatbot chat channel"
chatgptMusicChannelDelete = "This command will turn off chatbot music channel"
chatgptPublicThread = "This command will make a public thread for chatbot"
chatgptPrivateThread = "This command will make a private thread for chatbot"
chatgptDeleteThread = "This command will delete the thread for chatbot"